mss-boot-io/mss-boot-admin

.github/PULL_REQUEST_TEMPLATE.md, README.md, apis/option.go, cmd/migrate/migration/system/1691804837583_tables.go, cmd/migrate/migration/system/1691847581348_migrate.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, dto/option.go, models/option.go
=> :sparkles: feat(option): enabled

.github/workflows/ci.yml, .github/workflows/mirror.yml, .github/workflows/release.yml, Dockerfile.amd64, Dockerfile.arm64, README.md, README.zh-CN.md, cmd/server/server.go, config/config.go, go.mod
=> :sparkles: feat: add release workflow

.github/workflows/ci.yml, .github/workflows/release.yml
=> :bug: fix: upload file to release

.github/workflows/release.yml
=> :bug: fix: release upload binary 

Dockerfile
=> change start cmd

.github/workflows/release.yml
=> fix release body

go.mod, go.sum
=> :arrow_up: update mss-boot version

app/admin/apis/language.go, app/admin/models/user.go, cmd/migrate/migration/system/1691847581348_migrate.go
=> :bug: fix: github login error

app/admin/apis/department.go, app/admin/apis/menu.go, app/admin/apis/model.go, app/admin/apis/post.go, app/admin/dto/department.go, app/admin/dto/post.go, app/admin/models/department.go, app/admin/models/menu.go, app/admin/models/post.go, app/admin/models/tenant.go, cmd/migrate/migration/system/1691804837583_tables.go, go.mod, go.sum, middleware/auth.go, pkg/tree.go
=> :sparkles: feat: add department and post

app/admin/apis/department.go, app/admin/apis/menu.go, app/admin/dto/menu.go, go.mod, go.sum
=> :bug: fix: department swagger

app/admin/apis/department.go, app/admin/apis/menu.go, app/admin/apis/post.go, app/admin/dto/department.go, app/admin/dto/post.go, app/admin/models/department.go, app/admin/models/post.go, app/admin/models/tenant_migrate.go
=> :sparkles: feat: org enabled

cmd/server/server.go, config/application.yml
=> :sparkles: feat: default local config

app/admin/apis/app_config.go, app/admin/apis/user_config.go, app/admin/dto/user_config.go, app/admin/models/app_config.go, app/admin/models/tenant_migrate.go, app/admin/models/user_config.go, app/admin/service/user_config.go, center/default.go, center/type.go, cmd/server/server.go, config/application.yml, config/locker.go
=> :sparkles: feat: user config enabled

app/admin/apis/user_config.go, app/admin/models/tenant.go, app/admin/models/user.go, app/admin/service/app_config.go, app/admin/service/user_config.go
=> :bug: fix: app config

app/admin/models/task.go, app/admin/models/tenant.go, app/admin/models/type.go, go.mod, go.sum, middleware/auth.go
=> :sparkles: feat: support data scope

storage/queue/kafka.go
=> :bug: fix: consumer empty ptr

storage/queue/kafka.go
=> :bug: fix: consumer

middleware/auth.go, models/app_config.go
=> :bug: fix: app config cache error

config/queue.go, storage/queue/kafka.go
=> fix: miss kafka version and options

config/queue.go, storage/option.go, storage/queue/kafka.go
=> feat: support select partition

storage/queue/kafka.go
=> :art: code lint

apis/storage.go
https://github.com/mss-boot-io/mss-boot-admin/issues/41
=> :sparkles: feat: storage enabled

.github/workflows/ci.yml
=> :bug: fix: workflow error

apis/user_config.go, go.mod, go.sum, models/field.go
https://github.com/mss-boot-io/mss-boot-admin/issues/70
=> :sparkles: feat: update virtual model than update table

apis/virtual.go, cmd/migrate/migration/system/1691847581348_migrate.go, go.mod, go.sum, models/model.go
=> 💥 feat(vm): vm enabled

config/application.yml, config/queue.go, models/field.go
=> :bug: fix: aws token get too many times

apis/user.go
=> 💥 feat(login): auto login enabled

config/queue.go, go.mod
=> :bug: fix: kafka tls

.github/workflows/release.yml, .github/workflows/swagger.yml
=> :arrow_up: update go version

compose/kafka/docker-compose.yml, config/queue.go, storage/queue/kafka.go, storage/queue/kafka_scram_client.go
=> :bug: fix: support kafka scram sha512

storage/cache/context.go
=> :bug: fix: swagger

config/queue.go
=> :bug: fix: msk iam

config/queue.go
=> :bug: fix: msk iam expire

.github/workflows/ci.yml, apis/post.go
=> :bug: fix: post list error

cmd/migrate/migrate.go, go.mod, go.sum, middleware/auth.go, models/app_config.go, router/router.go
=> 🐛 fix: skip cache disabled

go.mod, go.sum
=> :bug: fix: mysql connection too many

middleware/auth.go
=> :bug: fix: data scope error

cmd/migrate/migrate.go, models/tenant.go
=> :bug: fix: migrate not found tenant table

models/user.go
=> :bug: fix: user edit error

config/application.yml, models/app_config.go, models/user.go
https://github.com/mss-boot-io/mss-boot-admin/issues/103
=> :bug: fix: tenant control

apis/menu.go, config/application.yml, models/tenant.go
https://github.com/mss-boot-io/mss-boot-admin/issues/108
=> :bug: fix: binding api error

apis/system_config.go, apis/tenant.go, center/type.go, go.mod, go.sum, middleware/auth.go, models/tenant.go
=> :bug: fix: tenant auth scope

apis/option.go
=> :bug: fix: option api data scope (#113)

.github/workflows/ci.yml, README.md, README.zh-CN.md
=> :bug: fix: ignore commit unit coverage error

apis/role.go
目前casbin规则表存储的API字段为Path，应该存储Name
=> :bug: fix: casbin rule error

apis/tenant.go, center/default.go, center/type.go, cmd/migrate/migration/system/1691847581348_migrate.go, cmd/server/server.go, models/tenant_migrate.go
=> :sparkles: feat: support tenant migrator

apis/user.go, go.mod, go.sum, middleware/auth.go, models/user.go, models/user_auth_token.go
=> :bug: fix:  access token index error

models/user.go
=> :bug: feat: support person access token no need domain

models/user.go
=> :bug: fix: github login group empty error

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/custom_issue.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
=> :sparkles: feat: add issue template

.github/PULL_REQUEST_TEMPLATE.md, go.mod, go.sum, models/menu.go
Fixes #147 
* Hardware:
* Toolchain:
* SDK:
=> :sparkles: feat: support delete all menu and it's children

Makefile, apis/user.go, dto/user.go, storage/cache/verify_code.go
Fixes #152 
* Hardware:
* Toolchain:
* SDK:
=> :sparkles: feat: support reset password by email

cmd/migrate/migrate.go, cmd/migrate/migration/system/1691847581348_migrate.go, models/user.go
* Hardware:
* Toolchain:
* SDK:
=> :bug: fix: appconfig enabled

apis/department.go, apis/menu.go, apis/post.go, go.mod, go.sum
=> :bug: fix: fix page

cmd/server/server.go
=> :sparkles: feat: local stage forces the use of local mode configuration

models/task.go
=> :sparkles: feat: add stage env

cmd/server/server.go, models/task.go
=> :bug: fix: list task default

apis/user.go, dto/user.go, models/user.go
=> feat: support binding lark account

models/user_auth_token.go
=> :bug: fix: person access token expire time error

models/task.go, models/tenant_migrate.go
* Hardware:
* Toolchain:
* SDK:
=> feat: Add task feature map and update permission path names

models/tenant_migrate.go
* Hardware:
* Toolchain:
* SDK:
=> fix: update menu path for department and adjust post sort order

models/tenant_migrate.go
* Hardware:
* Toolchain:
* SDK:
=> fix: correct menu path for post to plural form

models/task.go
* Hardware:
* Toolchain:
* SDK:
=> fix: handle nil command in task creation to prevent panic

apis/role.go
* Hardware:
* Toolchain:
* SDK:
=> :bug: fix: update permission path in AddPermissionForUser method

apis/language.go, go.mod, go.sum, service/app_config.go
fix: ensure non-empty results before returning from cache retrieval
* Hardware:
* Toolchain:
* SDK:
=> fix: ensure non-empty results before returning from cache retrieval
